name: Generate Screenshots
on:
  workflow_dispatch:
  push:

jobs:
  create_screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Project setup
      uses: bpmn-io/actions/setup@latest
    - name: Prepare Camunda 8 cluster
      run: npm run prepare-cluster
      env:
        CAMUNDA_CONSOLE_CLIENT_ID: ${{ secrets.CAMUNDA_CONSOLE_CLIENT_ID }}
        CAMUNDA_CONSOLE_CLIENT_SECRET: ${{ secrets.CAMUNDA_CONSOLE_CLIENT_SECRET }}
        CAMUNDA_CLUSTER_ID: ${{ secrets.CAMUNDA_CLUSTER_ID }}
    - name: Take Screenshots
      run: xvfb-run npm run start:ci
      env:
        CLUSTER_URL: ${{ secrets.CLUSTER_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        OAUTH_URL: ${{ secrets.OAUTH_URL }}
        MAX_PARALLEL_EXECUTIONS: 5
    - name: Archive Camunda 8 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: camunda-docs
        path: camunda-docs
    - name: Archive Camunda 7 (manual) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: camunda-docs-manual
        path: camunda-docs-manual
    - name: Archive Camunda 7 (static) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: camunda-docs-static
        path: camunda-docs-static

